# Generated by Django 5.0.1 on 2024-04-03 14:44

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('date', models.DateField(validators=[api.models.validate_future_date])),
                ('location', models.CharField(max_length=20)),
            ],
        ),
    ]
